### PR TITLE
Refine the example code in doc

### PR DESCRIPTION
**Pull request by FrostML**
Refine the doc of create_global_var, pad, pad_constant_like and pad2d to make it consistent with en doc.
Related to [Paddle #23549](https://github.com/PaddlePaddle/Paddle/pull/23549)

### CODE REVIEW

**Comment by FrostML** [comment]
* create_global_var:
cn_doc:
image
en_doc:
image

**Comment by FrostML** [comment]
* pad
cn_doc:
image
image

en_doc:
image
image

**Comment by FrostML** [comment]
* pad_constant_like
cn_doc:
image
image
image

en_doc:
image
image
image

**Comment by FrostML** [comment]
* pad2d
cn_doc:
image
image
en_doc:
image

image

**Review by Boyan-Liu — APPROVED** [review]

**Pull request merged**
