### PR TITLE
Fix some op API document, paddle tools group.

### PR DESCRIPTION
**Pull request by wawltor**
test=document_preview
Fix the op API of diag, greater_equal, greater_than, less_equal, linspace, not_equal, rank, reduce_all, reduce_any, rsqrt, sign, unique_with_counts, where, zeros_like.

### CODE REVIEW

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by wawltor** [comment]
image

**Comment by jiweibo** [comment]
@wawltor greater_than less_equal等op，返回类型是不是应该是bool？

**Comment by wawltor** [comment]
> @wawltor greater_than less_equal等op，返回类型是不是应该是bool？

是的 写的有问题，我修正一下。

**Review by nepeplwu — APPROVED** [review]

**Pull request merged**
