### PR TITLE
update install doc to release 1.6.1, test=develop

### PR DESCRIPTION
**Pull request by JepsonWong**
update install doc to release 1.6.1.

### CODE REVIEW

**Review by phlrain — APPROVED** [review]

**Comment by JepsonWong** [comment]
image

**Comment by JepsonWong** [comment]
image

**Comment by JepsonWong** [comment]
image

image

image

**Comment by JepsonWong** [comment]
image

image

**Comment by JepsonWong** [comment]
image
image
image
image

**Comment by JepsonWong** [comment]
image

**Review by saxon-zh — APPROVED** [review]

**Comment by adaxi987** [comment]
LGTM

**Review by hutuxian — APPROVED** [review]

**Pull request merged**
