### PR TITLE
Add paddle.distributed.shard_layer API cn doc

### PR DESCRIPTION
**Pull request by chenwhql**
related PR: https://github.com/PaddlePaddle/Paddle/pull/57604

image

### CODE REVIEW

**Review by sunzhongkai588 — APPROVED** [review]
LGTM for docs

**Comment by GhostScreaming** [comment]
LGTM

**Review by LiYuRio — APPROVED** [review]
LGTM

**Review by yangxiaoyu14 — COMMENTED** [review]
LGTM

**Pull request merged**
