### PR TITLE
add doc for erf op

### PR DESCRIPTION
**Pull request by iclementine**
1. add doc for erf op

Screenshot_2020-01-02 erf — fluiddoc dev 文档

### CODE REVIEW

**Comment by suytingwan** [comment]
hi，what to do with fluiddoc compiling failed? can it be merged still?

**Comment by iclementine** [comment]
> hi，what to do with fluiddoc compiling failed? can it be merged still?

I'm still waiting for the PR for erf_op to be approved.

**Review by kuke — APPROVED** [review]
LGTM

**Review by Boyan-Liu — APPROVED** [review]
LGTM

**Review by lanxianghit — APPROVED** [review]
LGTM

**Pull request merged**
