### PR TITLE
Update LoDTensorArray_cn

### PR DESCRIPTION
**Pull request by zhiqiu**
Update paddle.fluid.LoDTensorArray and paddle.fluid.LoDTensorArray.append()

### CODE REVIEW

**Comment by zhiqiu** [comment]
(1) paddle.fluid.LoDTensorArray
image

(2) paddle.fluid.LoDTensorArray.append
image

**Comment by zq19** [comment]
请将PR填写到API整改修复进度表，方便统计进度。

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Review by lanxianghit — APPROVED** [review]
LGTM

**Pull request merged**
