### PR TITLE
update TraceLayer save_inference_model api doc and dygraph_to_static example code

### PR DESCRIPTION
**Pull request by CtfGo**
update TraceLayer save_inference_model api doc and the example code of dygraph_to_static guide doc

### CODE REVIEW

**Comment by CtfGo** [comment]
image

**Comment by CtfGo** [comment]
image
image

**Review by chenwhql — APPROVED** [review]

**Review by saxon-zh — APPROVED** [review]
LGTM

**Review by zhhsplendid — APPROVED** [review]
LGTM

**Comment by CtfGo** [comment]
The new api has been merged with https://github.com/PaddlePaddle/Paddle/pull/31989

**Pull request merged**
