### PR TITLE
Add qat_init API into fleet doc

### PR DESCRIPTION
**Pull request by leo0519**
### PR types ###
New API

### PR changes ###
Docs

### Describe ###
There is a new API `qat_init` for `paddle.distributed.fleet`.
This PR added `qat_init` description into the document.

### CODE REVIEW

**Review by onecatcn — APPROVED** [review]
LGTM

**Comment by leo0519** [comment]
Hi @onecatcn , the CI Docs-NEW needs approval. Could you help contact one of TMP for approval?
```bash
You must have one TPM (jzhang533/ZhangJun or momozi1996/MoYan or dingjiaweiww/DingJiaWei or Ligoml/LiMengLiu or sunzhongkai588/SunZhongKai) approval for the api change! docs/api/paddle for the management reason of API interface and API document.
```

**Review by jzhang533 — APPROVED** [review]
lgtm

**Comment by onecatcn** [comment]
@leo0519 can you rerun the CI?

**Pull request merged**
