### PR TITLE
[MKL-DNN] Tensors conversion design doc

### PR DESCRIPTION
**Pull request by jczaja**
This is the same as #1132 , but I could not reopen so new PR was created.

This is first in a series of documents describing architecture of mkl-dnn integration. It is meant to be useful for PaddlePaddle developers and mkl-dnn integration maintainers in particular.

Rendered(suitable for reading) version of document can be seen at:
https://github.com/jczaja/Paddle/blob/prv-mkldnn-doc-data-transformation/paddle/fluid/operators/mkldnn/doc/data_transformation/data_transform.md

@grygielski , @bingyanghuang Please review

### CODE REVIEW

**Review by grygielski — APPROVED** [review]
LGTM

**Comment by jczaja** [comment]
@luotao1 Please review

**Comment by luotao1** [comment]
@jczaja We will skip the CI check of directory `doc/fluid/design/mkldnn` change at first before merging this PR.

**Review by luotao1 — APPROVED** [review]
LGTM

**Pull request merged**
