### PR TITLE
update install doc for 1.5.2, test=release/1.5

### PR DESCRIPTION
**Pull request by JepsonWong**
update install doc for 1.5.2.
1. Tables.md and index_cn.rst: update the paddle package to 1.5.2 for linux/mac.
2. index_cn.rst: windows support CUDA10.0.

### CODE REVIEW

**Comment by JepsonWong** [comment]
index_cn

image

image

table

**Comment by adaxi987** [comment]
LGTM

**Comment by adaxi987** [comment]
LGTM

**Review by JiabinYang — APPROVED** [review]
GTM

**Review by hutuxian — APPROVED** [review]

**Review by frankwhzhang — APPROVED** [review]

**Pull request merged**
