### PR TITLE
[IPU] update paddle.static.IpuStrategy

### PR DESCRIPTION
**Pull request by gglin001**
1. rename `batch_size` to `micro_batch_size` in `set_graph_config()`
2. add `enable_pattern()` and `disable_pattern()`

文档预览链接：http://10.136.157.23:8090/documentation/docs/zh/faq/index_cn.html?reviewVersion=jenkins-doc-review-2112

API文档 > paddle.static > IpuStrategy

### CODE REVIEW

**Comment by gglin001** [comment]
生成的预览如下

中文
cn

en
en

**Review by qili93 — APPROVED** [review]
LGTM

**Review by qili93 — APPROVED** [review]
LGTM

**Review by Ligoml — APPROVED** [review]
LGTM for docs

**Pull request merged**
