### PR TITLE
change fluid.layers.data to fluid.data in api_cn for retinanet_target_assign, sigmoid_focal_loss, retinanet_detection_output.

### PR DESCRIPTION
**Pull request by FlyingQianMM**
test=document_preview
change `fluid.layers.data` to `fluid.data` in api_cn for retinanet_target_assign, sigmoid_focal_loss, retinanet_detection_output.

### CODE REVIEW

**Comment by FlyingQianMM** [comment]
2404514ff83d7a0ebf1a212f1057fd57
826b1fbcdfa385df77bb384fb12d1945

**Comment by FlyingQianMM** [comment]
da1805418e3ecfc412c2e968987a8099

**Comment by FlyingQianMM** [comment]
95f77b09e2f904ac1d7039aca120dde6
34f9e87aaf62889655b34b8188517303

**Review by heavengate — APPROVED** [review]
LG API

**Pull request merged**
