### PR TITLE
Modify compare op Doc

### PR DESCRIPTION
**Pull request by SunAhong1993**

### CODE REVIEW

**Comment by SunAhong1993** [comment]
greater_equal
image
greater_than
image
equal
image
not_equal
image
less_equal
image

**Comment by SunAhong1993** [comment]
equal

greate_equal
greate_than
less_equal
not_equal

**Comment by SunAhong1993** [comment]
greater_equal
image
greater_than
image
equal
image
less_equal
image
not_equal
image

**Review by Boyan-Liu — APPROVED** [review]
LGTM

**Pull request merged**
