### PR TITLE
Clarify data layout for PaddlePaddle CPU kernels.

### PR DESCRIPTION
**Pull request by arogowie-intel**
PR types
maintenance 
PR changes
doc
Describe
In doc part regarding design of NHWC support for MKLDNN, I've clarified what data layout is used for learnable parameters and what for operator input signals in PaddlePaddle CPU kernels.

### CODE REVIEW

**Comment by arogowie-intel** [comment]
@jczaja Please review.

**Comment by jczaja** [comment]
@arogowie-intel Excellent! Much clearer now. LGTM

**Comment by arogowie-intel** [comment]
@jczaja I don't have permissions to ask any one for review, moreover don't know who to ask. Could you help?

**Comment by jczaja** [comment]
@luotao1 Could you please review this one?

**Review by luotao1 — APPROVED** [review]

**Pull request merged**
