### PR TITLE
GRU design doc of oneDNN kernels

### PR DESCRIPTION
**Pull request by jczaja**
This is oneDNN RNN(GRU, LSTM) kernels architecture

### CODE REVIEW

**Review by jakpiase — APPROVED** [review]
LGTM

**Comment by lidanqing-vv** [comment]
Hi, @baoachun  could you please help merge this design doc PR. It is very good and clear explanation for GRU and I think it is a good reference for other RNN ops.

**Comment by lidanqing-vv** [comment]
@Aganlengzi 可以帮忙合入一下哈。可以作为后面其他各类RNN op集成oneDNN 和oneDNN INT8在X86上的参考

**Review by Aganlengzi — APPROVED** [review]
LGTM

**Pull request merged**
