### PR TITLE
polish cn document of unique_name

### PR DESCRIPTION
**Pull request by zhiqiu**
This PR updates Chinese document of three APIs, i.e., fluid.unique_name.generate(), fluid.unique_name.switch() and fluid.unique_name.guard().

### CODE REVIEW

**Comment by zhiqiu** [comment]
fluid.unique_name.generate()
image

fluid.unique_name.switch() 
image

fluid.unique_name.guard()
image

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Comment by zhiqiu** [comment]
fluid.unique_name.guard()
image

fluid.unique_name.switch()
image

**Review by sneaxiy — APPROVED** [review]
LGTM.

**Review by XiaoguangHu01 — APPROVED** [review]

**Comment by zhiqiu** [comment]
add example code for switch().
image

**Review by sneaxiy — APPROVED** [review]

**Pull request merged**
