### PR TITLE
Modified the wrong path of loading pictures , test =develop

### PR DESCRIPTION
**Pull request by silingtong123**
修改了DyGraph.md中加载图片的错误路径，使其与PaddleBook保持统一

### CODE REVIEW

**Comment by JiabinYang** [comment]
> 修改了DyGraph.md中模型评估部分的代码，和PaddleBook保持统一，对应卡片为DLTP-1760

Maybe we don't need to add cards info in PR

**Review by wanghaoshuang — APPROVED** [review]

**Comment by silingtong123** [comment]
> > 修改了DyGraph.md中模型评估部分的代码，和PaddleBook保持统一，对应卡片为DLTP-1760
> 
> Maybe we don't need to add cards info in PR

已修改

**Review by heavengate — APPROVED** [review]

**Comment by lanxianghit** [comment]
请参照PR规范修改一下标题

**Comment by silingtong123** [comment]
> 请参照PR规范修改一下标题

已修改

**Pull request merged**
