### PR TITLE
Add Design Doc: oneDNN Bfloat16 support

### PR DESCRIPTION
**Pull request by wozna**
Design doc about:
* bfloat16 data type
* oneDNN bfloat16 support 
* bfloat16 inference enablement in PaddlePaddle

### CODE REVIEW

**Comment by jczaja** [comment]
@wozna It is excellent contribution. The only thing I would add is to mention PaddlePaddle version which was used for taking measures.

**Review by arlesniak — APPROVED** [review]
LGTM

**Comment by wozna** [comment]
> @wozna It is excellent contribution. The only thing I would add is to mention PaddlePaddle version which was used for taking measures.

I am waiting for the merge of https://github.com/PaddlePaddle/Paddle/pull/29155 with bfloat16 models to ensure the version.

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by wozna** [comment]
@luotao1  Could you please see this document and do a review? This document describes all the information from `bfloat16` that has been added up to that time.

**Review by luotao1 — APPROVED** [review]
LGTM！！

**Pull request merged**
