### PR TITLE
update paddle.hub

### PR DESCRIPTION
**Pull request by lyuwenyu**
- update paddle.hub 

image

### CODE REVIEW

**Review by jzhang533 — APPROVED** [review]
LGTM

**Comment by wadefelix** [comment]
@lyuwenyu 在 https://github.com/PaddlePaddle/docs/blob/develop/ci_scripts/Dockerfile 的requirements段加这个tqdm依赖即可

**Review by TCChenlong — APPROVED** [review]
LGTM

**Comment by lyuwenyu** [comment]
> @lyuwenyu 在 https://github.com/PaddlePaddle/docs/blob/develop/ci_scripts/Dockerfile 的requirements段加这个tqdm依赖即可

@wadefelix 
opencv 导入错误 -.-

**Pull request merged**
