### PR TITLE
fix code examples and docs

### PR DESCRIPTION
**Pull request by baiyfbupt**
fix code examples and docs.
英文文档PR： https://github.com/PaddlePaddle/Paddle/pull/28636

### CODE REVIEW

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Comment by baiyfbupt** [comment]
image
image

**Review by TCChenlong — APPROVED** [review]
LGTM

**Pull request merged**
