### PR TITLE
fix examples

### PR DESCRIPTION
**Pull request by ceci3**
fix chinese examples for instance_norm, LeakyReLU, weight_norm, remove_weight_norm, SyncBatchNorm
english docs: https://github.com/PaddlePaddle/Paddle/pull/29019

### CODE REVIEW

**Comment by ceci3** [comment]
image
remove_weight_norm

**Comment by ceci3** [comment]
image
weight_norm

**Comment by ceci3** [comment]
image
SyncBatchNorm

**Comment by ceci3** [comment]
image
LeakyReLU

**Comment by ceci3** [comment]
image
instance_norm

**Review by jzhang533 — APPROVED** [review]
lgtm

**Pull request merged**
