### PR TITLE
update english installation documents

### PR DESCRIPTION
**Pull request by JepsonWong**
update english installation documents.
* Tables_en.md
* compile_CentOS_en.md
* compile_MacOS_en.md
* compile_Ubuntu_en.md
* index_en.rst
* install_CentOS_en.md
* install_Docker_en.md
* install_Ubuntu_en.md

### CODE REVIEW

**Comment by JepsonWong** [comment]
image

**Comment by JepsonWong** [comment]
image

**Comment by JepsonWong** [comment]
image

**Comment by JepsonWong** [comment]
image

**Review by saxon-zh — APPROVED** [review]

**Pull request merged**
